const Storage = {
  get(key, def) {
    try {
      const d = localStorage.getItem(key);
      return d ? JSON.parse(d) : def || [];
    } catch {
      return def || [];
    }
  },
  set(key, val) {
    localStorage.setItem(key, JSON.stringify(val));
  },
  getUsers: () => Storage.get("cf_users"),
  saveUsers: (u) => Storage.set("cf_users", u),
  getIssues: () => Storage.get("cf_issues"),
  saveIssues: (i) => Storage.set("cf_issues", i),
  getNotifications: () => Storage.get("cf_notifications"),
  saveNotifications: (n) => Storage.set("cf_notifications", n),
  getAnnouncements: () => Storage.get("cf_announcements"),
  saveAnnouncements: (a) => Storage.set("cf_announcements", a),
  getSLASettings: () =>
    Storage.get("cf_sla", { LOW: 72, MEDIUM: 48, HIGH: 24, CRITICAL: 8 }),
  saveSLASettings: (s) => Storage.set("cf_sla", s),
  getCategories: () =>
    Storage.get("cf_categories", [
      "Electrical",
      "Plumbing",
      "Carpentry",
      "HVAC",
      "IT/Network",
      "Cleaning",
      "Furniture",
      "Other",
    ]),
  saveCategories: (c) => Storage.set("cf_categories", c),

  initDemoData() {
    if (localStorage.getItem("cf_initialized")) return;
    const now = Date.now();
    const h = 3600000,
      d = 86400000;

    const users = [
      {
        id: "u1",
        name: "Alice Student",
        email: "student@campusfix.demo",
        password: "password123",
        role: "USER",
        studentId: "STU2024001",
        department: "Computer Science",
        phone: "555-0100",
        status: "ACTIVE",
      },
      {
        id: "u2",
        name: "Bob Staff",
        email: "staff@campusfix.demo",
        password: "password123",
        role: "USER",
        studentId: "STF001",
        department: "Administration",
        phone: "555-0101",
        status: "ACTIVE",
      },
      {
        id: "u3",
        name: "Carol Student",
        email: "carol@campusfix.demo",
        password: "password123",
        role: "USER",
        studentId: "STU2024002",
        department: "Engineering",
        phone: "555-0102",
        status: "ACTIVE",
      },
      {
        id: "w1",
        name: "Dave Maintenance",
        email: "worker@campusfix.demo",
        password: "password123",
        role: "WORKER",
        specialization: "General",
        status: "ACTIVE",
      },
      {
        id: "w2",
        name: "Eve Electrician",
        email: "eve@campusfix.demo",
        password: "password123",
        role: "WORKER",
        specialization: "Electrical",
        status: "ACTIVE",
      },
      {
        id: "w3",
        name: "Frank Plumber",
        email: "frank@campusfix.demo",
        password: "password123",
        role: "WORKER",
        specialization: "Plumbing",
        status: "ACTIVE",
      },
      {
        id: "a1",
        name: "Grace Admin",
        email: "admin@campusfix.demo",
        password: "password123",
        role: "ADMIN",
        status: "ACTIVE",
      },
    ];
    Storage.saveUsers(users);

    const issues = [
      {
        id: "i1",
        ref: "CF-2026-00001",
        title: "Broken AC in Library",
        description:
          "AC making loud noise and not cooling properly in the main reading hall.",
        category: "HVAC",
        building: "Library",
        room: "Main Hall",
        priority: "HIGH",
        status: "IN_PROGRESS",
        reporterId: "u1",
        assignedWorkerId: "w1",
        deadline: now + 12 * h,
        createdAt: now - 2 * d,
        resolvedAt: null,
        closedAt: null,
        attachments: [],
        history: [
          {
            status: "SUBMITTED",
            date: now - 2 * d,
            note: "Submitted",
            by: "u1",
          },
          {
            status: "VERIFIED",
            date: now - 2 * d + 2 * h,
            note: "Verified",
            by: "a1",
          },
          {
            status: "ASSIGNED",
            date: now - 1 * d,
            note: "Assigned to Dave",
            by: "a1",
          },
          {
            status: "IN_PROGRESS",
            date: now - 12 * h,
            note: "Started work",
            by: "w1",
          },
        ],
        progressNotes: [
          {
            note: "Parts ordered, waiting for delivery.",
            date: now - 6 * h,
            by: "w1",
          },
        ],
        verification: null,
        rejectionReason: null,
      },
      {
        id: "i2",
        ref: "CF-2026-00002",
        title: "Leaking faucet in restroom",
        description: "Faucet dripping constantly, wasting water.",
        category: "Plumbing",
        building: "Science Block",
        room: "Restroom 2",
        priority: "MEDIUM",
        status: "RESOLVED",
        reporterId: "u2",
        assignedWorkerId: "w3",
        deadline: now + 24 * h,
        createdAt: now - 3 * d,
        resolvedAt: now - 6 * h,
        closedAt: null,
        attachments: [],
        history: [
          {
            status: "SUBMITTED",
            date: now - 3 * d,
            note: "Submitted",
            by: "u2",
          },
          {
            status: "VERIFIED",
            date: now - 3 * d + h,
            note: "Verified",
            by: "a1",
          },
          { status: "ASSIGNED", date: now - 2 * d, note: "Assigned", by: "a1" },
          {
            status: "IN_PROGRESS",
            date: now - 1 * d,
            note: "Started",
            by: "w3",
          },
          {
            status: "RESOLVED",
            date: now - 6 * h,
            note: "Faucet replaced.",
            by: "w3",
          },
        ],
        progressNotes: [],
        verification: null,
        rejectionReason: null,
      },
      {
        id: "i3",
        ref: "CF-2026-00003",
        title: "Flickering lights in lecture hall",
        description: "Lights flickering intermittently during lectures.",
        category: "Electrical",
        building: "Engineering Block",
        room: "Lecture Hall 3",
        priority: "MEDIUM",
        status: "ASSIGNED",
        reporterId: "u3",
        assignedWorkerId: "w2",
        deadline: now + 36 * h,
        createdAt: now - 1 * d,
        resolvedAt: null,
        closedAt: null,
        attachments: [],
        history: [
          {
            status: "SUBMITTED",
            date: now - 1 * d,
            note: "Submitted",
            by: "u3",
          },
          {
            status: "VERIFIED",
            date: now - 20 * h,
            note: "Verified",
            by: "a1",
          },
          {
            status: "ASSIGNED",
            date: now - 18 * h,
            note: "Assigned to Eve",
            by: "a1",
          },
        ],
        progressNotes: [],
        verification: null,
        rejectionReason: null,
      },
      {
        id: "i4",
        ref: "CF-2026-00004",
        title: "Broken door lock",
        description: "Door lock not engaging properly. Security concern.",
        category: "Carpentry",
        building: "Library",
        room: "Room 101",
        priority: "CRITICAL",
        status: "SUBMITTED",
        reporterId: "u1",
        assignedWorkerId: null,
        deadline: now + 8 * h,
        createdAt: now - 2 * h,
        resolvedAt: null,
        closedAt: null,
        attachments: [],
        history: [
          {
            status: "SUBMITTED",
            date: now - 2 * h,
            note: "Submitted",
            by: "u1",
          },
        ],
        progressNotes: [],
        verification: null,
        rejectionReason: null,
      },
      {
        id: "i5",
        ref: "CF-2026-00005",
        title: "Wi-Fi dead zone in cafeteria",
        description: "No Wi-Fi signal in the east corner of the cafeteria.",
        category: "IT/Network",
        building: "Student Center",
        room: "Cafeteria",
        priority: "LOW",
        status: "CLOSED",
        reporterId: "u2",
        assignedWorkerId: "w1",
        deadline: now - 1 * d,
        createdAt: now - 7 * d,
        resolvedAt: now - 3 * d,
        closedAt: now - 2 * d,
        attachments: [],
        history: [
          {
            status: "SUBMITTED",
            date: now - 7 * d,
            note: "Submitted",
            by: "u2",
          },
          { status: "VERIFIED", date: now - 6 * d, note: "Verified", by: "a1" },
          { status: "ASSIGNED", date: now - 5 * d, note: "Assigned", by: "a1" },
          {
            status: "IN_PROGRESS",
            date: now - 4 * d,
            note: "Started",
            by: "w1",
          },
          {
            status: "RESOLVED",
            date: now - 3 * d,
            note: "AP installed",
            by: "w1",
          },
          {
            status: "CLOSED",
            date: now - 2 * d,
            note: "Verified by reporter",
            by: "u2",
          },
        ],
        progressNotes: [],
        verification: { approved: true, date: now - 2 * d, by: "u2" },
        rejectionReason: null,
      },
      {
        id: "i6",
        ref: "CF-2026-00006",
        title: "Leaking faucet in restroom",
        description: "Another faucet leaking in the same restroom.",
        category: "Plumbing",
        building: "Science Block",
        room: "Restroom 2",
        priority: "MEDIUM",
        status: "SUBMITTED",
        reporterId: "u3",
        assignedWorkerId: null,
        deadline: now + 48 * h,
        createdAt: now - 1 * h,
        resolvedAt: null,
        closedAt: null,
        attachments: [],
        history: [
          {
            status: "SUBMITTED",
            date: now - 1 * h,
            note: "Submitted",
            by: "u3",
          },
        ],
        progressNotes: [],
        verification: null,
        rejectionReason: null,
      },
    ];
    Storage.saveIssues(issues);

    const notifs = [
      {
        id: "n1",
        userId: "u1",
        message: "Your issue CF-2026-00001 is now In Progress.",
        read: false,
        createdAt: now - 12 * h,
      },
      {
        id: "n2",
        userId: "w1",
        message: "New issue assigned: CF-2026-00001.",
        read: true,
        createdAt: now - 1 * d,
      },
      {
        id: "n3",
        userId: "a1",
        message: "New issue reported: CF-2026-00004.",
        read: false,
        createdAt: now - 2 * h,
      },
      {
        id: "n4",
        userId: "u2",
        message: "Issue CF-2026-00002 marked resolved. Please verify.",
        read: false,
        createdAt: now - 6 * h,
      },
      {
        id: "n5",
        userId: "a1",
        message: "New issue reported: CF-2026-00006.",
        read: false,
        createdAt: now - 1 * h,
      },
    ];
    Storage.saveNotifications(notifs);

    Storage.saveAnnouncements([
      {
        id: "ann1",
        title: "Water Shut-off Notice",
        content:
          "Water will be shut off in Science Block on Friday 8AM-12PM for pipe maintenance.",
        active: true,
        affectedArea: "Science Block",
        startDate: now - 1 * d,
        endDate: now + 5 * d,
      },
      {
        id: "ann2",
        title: "Library AC Maintenance",
        content:
          "Library AC system under maintenance. Expected completion: Wednesday.",
        active: true,
        affectedArea: "Library",
        startDate: now - 2 * d,
        endDate: now + 3 * d,
      },
    ]);

    localStorage.setItem("cf_initialized", "true");
  },
};
Storage.initDemoData();
